[tool.poetry]
name = "pvz-svc"
version = "0.1.0"
description = ""
authors = ["gal16v8d"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.109.1"
pymongo = "^4.6.1"
uvicorn = "^0.25.0"
python-dotenv = "^1.0.1"

[tool.poetry.group.dev.dependencies]
pylint = "^3.0.3"
pep8 = "^1.7.1"
autopep8 = "^2.0.4"
pytest = "^7.4.4"
mongomock = "^4.1.2"
httpx = "^0.26.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
